### ISSUE TITLE
feat: fix contributors list

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/helia-contributors#1]
```[tasklist]
### Tasks
- [ ] https://github.com/ipfs-shipyard/helia-contributors/issues/4
- [ ] https://github.com/ipfs-shipyard/helia-contributors/issues/6
- [ ] https://github.com/ipfs-shipyard/helia-contributors/issues/3
- [ ] https://github.com/ipfs-shipyard/helia-contributors/issues/5
```

**Comment by SgtPooki** [comment]
idk if we want to parse through all package.json deps and add all contributors from those.. may need a filter step or ‘ignore’ list because there are things like ‘multiformats’ and ‘p-defer’ and others that aren’t really helia specific.

This is captured in https://github.com/ipfs-shipyard/helia-contributors/issues/3
